#!/bin/env bash

set -e
shopt -s expand_aliases

BASE16_SHELL="$HOME/.config/base16-shell/"
eval "$("$BASE16_SHELL/profile_helper.sh")"

function main {
  if [[ "$1" == "" ]]; then
    THEME=$( ( IFS=$'\n'; echo "${THEMES[*]}" ) | dmenu)
  else
    THEME=$1
  fi


  # term
  _base16 "$HOME/.config/base16-shell/scripts/base16-$THEME.sh" "$THEME"

  # i3
  i3-theme "$THEME" > "$HOME/.config/i3/colors"
  i3-build-config
  i3-msg -q reload

}

function i3-build-config {
  cat "$HOME/.config/i3/base" "$HOME/.config/i3/gaps" "$HOME/.config/i3/colors" \
    > "$HOME/.config/i3/config"
}

function i3-theme {
  cat "$HOME/git/base16-i3/themes/base16-$1.config" \
    | sed -E "s/(focused_workspace +) +\$base.. +(\$base..)(.*)/\1\2 \2\3/g" \
    | sed '/status_command/a mode hide\nmodifier None'
}

THEMES=(
  3024
  apathy
  ashes
  atelier-cave-light
  atelier-cave
  atelier-dune-light
  atelier-dune
  atelier-estuary-light
  atelier-estuary
  atelier-forest-light
  atelier-forest
  atelier-heath-light
  atelier-heath
  atelier-lakeside-light
  atelier-lakeside
  atelier-plateau-light
  atelier-plateau
  atelier-savanna-light
  atelier-savanna
  atelier-seaside-light
  atelier-seaside
  atelier-sulphurpool-light
  atelier-sulphurpool
  atlas
  bespin
  black-metal-bathory
  black-metal-burzum
  black-metal-dark-funeral
  black-metal-gorgoroth
  black-metal-immortal
  black-metal-khold
  black-metal-marduk
  black-metal-mayhem
  black-metal-nile
  black-metal
  black-metal-venom
  brewer
  bright
  brogrammer
  brushtrees-dark
  brushtrees
  chalk
  circus
  classic-dark
  classic-light
  codeschool
  cupcake
  cupertino
  darktooth
  default-dark
  default-light
  dracula
  eighties
  embers
  flat
  fruit-soda
  github
  google-dark
  google-light
  grayscale-dark
  grayscale-light
  greenscreen
  gruvbox-dark-hard
  gruvbox-dark-medium
  gruvbox-dark-pale
  gruvbox-dark-soft
  gruvbox-light-hard
  gruvbox-light-medium
  gruvbox-light-soft
  harmonic-dark
  harmonic-light
  heetch-light
  heetch
  hopscotch
  ia-dark
  ia-light
  icy
  irblack
  isotope
  macintosh
  marrakesh
  material-darker
  material-lighter
  material-palenight
  material
  material-vivid
  materia
  mellow-purple
  mexico-light
  mocha
  monokai
  nord
  oceanicnext
  ocean
  onedark
  one-light
  outrun-dark
  papercolor-dark
  papercolor-light
  paraiso
  phd
  pico
  pop
  porple
  railscasts
  rebecca
  seti
  shapeshifter
  snazzy
  solarflare
  solarized-dark
  solarized-light
  spacemacs
  summerfruit-dark
  summerfruit-light
  tomorrow-night
  tomorrow
  tube
  twilight
  unikitty-dark
  unikitty-light
  woodland
  xcode-dusk
  zenburn
)

main "$@"
